Move checkbox-ce-oem snapcraft.yaml into contrib area (New)
canonical/checkbox pull request #1120
Opened 2024-03-27 14:42 UTC by zongminl

## Description

There were snapcraft.yaml files hosted on LP Git for checkbox-ce-oem to be built and published by LP build infra, as of now checkbox-provider-ce-oem has been hosted in the contrib area of monorepo we should also host snapcraft.yaml files on GH so checkbox-ce-oem snap can be built through GH workflow

Note: This PR only moves snapcraft.yaml files into GH, there hasn't been any changes with regard to building latest checkbox-ce-oem source from contrib area

## Resolved issues

https://warthogs.atlassian.net/browse/OEMQA-4135

## Documentation

## Tests

2024-03-28 00:31 UTC, baconYao requested changes
@zongminl Please take a look at my suggestions,

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic20/launchers/configure
> +snap connect $SNAP_NAME:provider-ipdt     checkbox20:provider-ipdt
Remove `provider-ipdt `
```suggestion
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic20/snap/hooks/configure
> +snap connect $SNAP_NAME:provider-ipdt     checkbox22:provider-ipdt
Remove `provider-ipdt `
```suggestion
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic22/launchers/configure
> +snap connect $SNAP_NAME:provider-ipdt     checkbox22:provider-ipdt
Remove `provider-ipdt `
```suggestion
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic22/snap/hooks/configure
> +snap connect $SNAP_NAME:provider-ipdt     checkbox22:provider-ipdt
Remove `provider-ipdt `
```suggestion
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_uc22/launchers/configure
> +snap connect $SNAP_NAME:provider-ipdt     checkbox22:provider-ipdt
Remove `provider-ipdt `
```suggestion
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic20/snap/snapcraft.yaml
> +version: '0.12-focal'
How about starting the version from `1.0`?
```suggestion
version: '1.0-focal'
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic22/snap/snapcraft.yaml
> +version: '0.12-jammy'
How about starting the version from `1.0`?
```suggestion
version: '1.0-jammy'
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_uc20/snap/snapcraft.yaml
> +version: '0.12-focal'
How about starting the version from `1.0`?
```suggestion
version: '1.0-focal'
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_uc22/snap/snapcraft.yaml
> +version: '0.12-jammy'
How about starting the version from 1.0?
```suggestion
version: '1.0-jammy'
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic22/launchers/wrapper_local
> +#export PATH="$PATH:$SNAP/usr/bin:$SNAP/usr/sbin:$SNAP/sbin:/snap/bin:/snap/checkbox-ce-oem/current/usr/bin/:/snap/checkbox-ce-oem/current/usr/sbin"
Remove useless `export`
```suggestion
```

2024-03-28 00:31 UTC, baconYao commented on contrib/checkbox-provider-ce-oem/series_classic22/launchers/wrapper_local
> +#export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/snap/checkbox-ce-oem/current/usr/lib/aarch64-linux-gnu"
Remove useless `export`
```suggestion
```

2024-03-28 02:35 UTC, rickwu666666 submitted a review, later dismissed
LGTM

2024-04-01 07:16 UTC, LiaoU3 approved these changes
+1

2024-04-01 07:19 UTC, baconYao approved these changes
+1

2024-04-01 07:19 UTC, merged