Add camera submission for multiple resolution test (New)
canonical/checkbox pull request #1256
Opened 2024-05-24 16:42 UTC by fernando79513

## Description

The camera_test.py script has been modified to store one image each time it runs the multiple_resolution test.
We have fixed some bugs, renamed some variables to increase clarity and added tests

## Resolved issues

https://warthogs.atlassian.net/browse/CHECKBOX-1369

## Documentation

N/A

## Tests

```
cd providers/base
manage.py test -u
```

2024-05-30 10:32 UTC, Hook25 requested changes
Nice, a few minor changes/suggestions, see what you think about them

2024-05-30 10:32 UTC, Hook25 commented on providers/base/bin/camera_test.py
> +        help="Output directory to store the images",
```suggestion
        help="Output directory to store a small debug image",
```

2024-05-30 10:32 UTC, Hook25 commented on providers/base/tests/test_camera_test.py
> +        )
```suggestion
        expected_str = textwrap.dedent(
            """
            Format: YUYV (YUYV)
            Resolutions: 640x480,320x240
            Format: fake (fake)
            Resolutions: 640x480
            """
        ).lstrip()
```

2024-05-30 10:32 UTC, Hook25 commented on providers/base/tests/test_camera_test.py
> +        )
(check if it works/formats is ok!)

2024-05-30 10:32 UTC, Hook25 commented on providers/base/tests/test_camera_test.py
> +
Oooups, was this forgotten?
```suggestion
```

2024-05-30 10:32 UTC, Hook25 commented on providers/base/bin/camera_test.py
> +            output, "resolution_test_image_{}.jpg".format(device_name)
Minor: on re-run this is overwritten, maybe we should put a `_{n}.jpg` at the end (you can simply add a len(list(glob(...)))`, also, consider pathlib.

2024-05-30 10:32 UTC, Hook25 commented on providers/base/units/camera/jobs.pxu
> +  [ -f "$PLAINBOX_SESSION_SHARE"/resolution_test_image_{name}.jpg ] &&
If you adopt the change (n at the end) to the `resolution_test_image_{name}_*.jpg`, consider updating this as well

2024-05-30 10:32 UTC, Hook25 commented on providers/base/units/camera/jobs.pxu
> +  [ -f "$PLAINBOX_SESSION_SHARE"/picam_6.jpg ] &&
Why is the name off/different here?

2024-05-30 10:43 UTC, fernando79513 commented on providers/base/tests/test_camera_test.py
> +        )
Yes, with the `lstrip()` it works fine

2024-06-03 14:21 UTC, Hook25 commented on providers/base/bin/camera_test.py
> +            output, "resolution_test_image_{}.jpg".format(device_name)
After what we decided, this is indeed good enough. If we will ever need the history we will go back to this

2024-06-03 14:22 UTC, Hook25 commented on providers/base/units/camera/jobs.pxu
> +  [ -f "$PLAINBOX_SESSION_SHARE"/picam_6.jpg ] &&
oh ok, ty for clarifying this

2024-06-03 14:22 UTC, Hook25 approved these changes

2024-06-03 14:53 UTC, merged