Add readme file for cases and environ variable for ce-oem-provider (New)
canonical/checkbox pull request #1312
Opened 2024-06-24 09:37 UTC by stanley31huang

## Description
Add readme file for cases and environ variable for ce-oem-provider

We would like to have a document to describe which environ variable has been defined in the checkbox-ce-oem provider

## Resolved issues
N/A

## Documentation
N/A

## Tests
N/A

2024-06-25 15:13 UTC, pieqq requested changes
This must have required a lot of work, unless you had some kind of script to generate the content!

A few comments:

- In the "Affected Test Cases" sections, I would point directly to the job in the pxu file. You can use relative links, and GitHub will understand them. Doing this will avoid a lot of duplicated data (`environ, summary, description, command`) that will probably go out of date quickly
- How do you plan on maintaining this? Are other contributors to ce-oem-provider aware they have to update the associated `md` files if they introduce a new environment key? Maybe you can add this to the [README file](https://github.com/canonical/checkbox/blob/main/contrib/checkbox-ce-oem/README.md).

2024-08-06 07:28 UTC, zongminl approved these changes
As the first step of capturing environ variables into README files, this PR looks good enough.
Some environ variables still missing detailed descriptions, this will be something to be fixed in the future.

2024-08-23 06:06 UTC, stanley31huang commented
@pieqq  I have updated the description to have an followup action to implement a script to keep these document up to date. Could you please review this PR again?

2025-02-13 15:41 UTC, pieqq approved these changes
This PR fell out of my radar. But as discussed before, it's good to land as is, and we'll see where this takes us.

2025-02-27 09:43 UTC, merged