Add an "Initial Stress Tests" category to distinguish tests that are prepared for stress tests (BugFix)
canonical/checkbox pull request #1368
Opened 2024-07-25 09:43 UTC by eugene-yujinwu

Fix: Two almost identical 'Stress Tests' lead to some confusion #1319
Add a new category named "Initial Stress Tests" to used for some initial tests of stress tests, such as init-boot-loop-data which used to create a baseline for other tests. 

## Description

## Resolved issues
Two almost identical 'Stress Tests' lead to some confusion #1319

## Documentation

## Tests

![initial-stress-tests-report](https://github.com/user-attachments/assets/336315f0-0a06-47e9-b7db-8da3c30c5cf8)
![initial-stress-tests](https://github.com/user-attachments/assets/39e5765c-422c-468a-a0b3-a6917125d5f3)

2024-07-26 03:40 UTC, zongminl requested changes
Compares to adding an additional category, I'd rather suggest to clean up the duplicated ones and use `com.canonical.plainbox::stress` for all the stress tests

2024-07-31 10:03 UTC, eugene-yujinwu commented
> Compares to adding an additional category, I'd rather suggest to clean up / remove the duplicated ones and use `com.canonical.plainbox::stress` for all the stress tests

@zongminl There are 2 test cases belong to catagory stress-tests: reboot-run-generator and init-boot-loop-data, and I just move them to com.canonical.plainbox::stress.  
The results would like this:
![Stress-test-new](https://github.com/user-attachments/assets/b8d848a3-b81f-4ab3-a88c-034fa41310fb)

2024-08-01 07:10 UTC, tomli380576 submitted a review, later dismissed
yay no more duplicate categories :D

2024-08-01 14:58 UTC, zongminl requested changes
- Please remove the unused `com.canonical.certification::stress-tests` category entirely
- There are still a few jobs using `com.canonical.certification::stress-tests` category, please also make the change for them
    - [stress/stress-ng-test-for-stressor-{stressor}](https://github.com/canonical/checkbox/blob/7ab7c0fea16478639e0d0ac915f5fc72720d14e6/providers/base/units/stress/stress-ng.pxu#L18)
    - [ce-oem-init-boot-loop-data](https://github.com/canonical/checkbox/blob/7ab7c0fea16478639e0d0ac915f5fc72720d14e6/contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/stress/boot.pxu#L1)

2024-08-06 07:11 UTC, eugene-yujinwu commented
> * Please remove the unused `com.canonical.certification::stress-tests` category entirely
> * There are still a few jobs using `com.canonical.certification::stress-tests` category, please also make the change for them
>   
>   * [stress/stress-ng-test-for-stressor-{stressor}](https://github.com/canonical/checkbox/blob/7ab7c0fea16478639e0d0ac915f5fc72720d14e6/providers/base/units/stress/stress-ng.pxu#L18)
>   * [ce-oem-init-boot-loop-data](https://github.com/canonical/checkbox/blob/7ab7c0fea16478639e0d0ac915f5fc72720d14e6/contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/stress/boot.pxu#L1)

@zongminl Per your comments, the stress-tests category was removed, and two tests mentioned was change to category com.canonical.plainbox::stress.

2024-08-06 08:02 UTC, zongminl approved these changes
LGTM, thank you

2024-08-06 08:07 UTC, merged