Make all rtcwake cmd can select the RTC_DEVICE_FILE from confing file
canonical/checkbox pull request #1395
Opened 2024-08-07 04:02 UTC by seankingyang

## Description
Modify all jobs will call the rtcwake cmd and didn't support for user to select which rtc device they want to use.
In rtcwake default will use the `rtc0`, and this change will also make if the `RTC_DEVICE_FILE` didn't define in config will also use the `rtc0`.

## Resolved issues

## Documentation

## Tests

2024-08-07 05:03 UTC, zongminl requested changes
I see you made changes to some config_var in checkbox-snap, but why the followings are not changed:

- common_series_classic
- series_uc16
- series_uc18
- series_uc20
- series_uc22

Also there's a typo to be fixed, see my inline comment

2024-08-07 14:25 UTC, LiaoU3 commented
I am wondering if there are multiple RTC like rtc1, how should we handle it?

2024-08-08 04:44 UTC, seankingyang commented on providers/base/units/stress/boot.pxu
> + rtcwake -v -d "${{RTC_DEVICE_FILE:-rtc0}}"--mode off -s "${{STRESS_BOOT_WAKEUP_DELAY:-120}}"
Thanks~~ fix it

2024-08-08 04:53 UTC, seankingyang commented on providers/base/units/stress/boot.pxu
> + rtcwake -v -d "${{RTC_DEVICE_FILE:-rtc0}}"--mode off -s "${{STRESS_BOOT_WAKEUP_DELAY:-120}}"
$ find . -name "config_vars"
./common_series_uc/config_vars
./series_uc24/config_vars
./series_classic22/config_vars
./series_classic16/config_vars
./series_classic18/config_vars
./series_classic24/config_vars
./series_classic20/config_vars
```

2024-08-08 05:40 UTC, zongminl approved these changes
LGTM

2024-08-08 07:36 UTC, merged