[checkbox-ce-oem] add test cases to validate those plug and slot interface defined in gadget snap (New)
canonical/checkbox pull request #1439
Opened 2024-08-29 04:44 UTC by stanley31huang

## Description
add test cases to validate those plug and slot interface defined in gadget snap

## Resolved issues
N/A

## Documentation
N/A

## Tests
Side-loading test results: https://certification.canonical.com/hardware/202406-34081/submission/389585/

2024-08-29 07:42 UTC, baconYao reviewed
How about we put `gadget_interface_schema.json` to `data` folder?

2024-08-29 07:54 UTC, baconYao requested changes

2024-08-29 07:54 UTC, baconYao commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/manifest.pxu
> +_name: Does platform has plugs and slots been defined in Gadget snap?
```suggestion
_name: Does platform have plugs and slots been defined in Gadget snap?
```

2024-08-29 07:54 UTC, baconYao commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
> +    Usage
What's the purpose of `Usage` here?

2024-08-29 07:54 UTC, baconYao commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/check_gadget_interface.py
> +def varify_slot_interface(name, interface):
```suggestion
def verify_slot_interface(name, interface):
```

2024-08-29 07:54 UTC, baconYao commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/check_gadget_interface.py
> +def varify_plug_interface(name, interface):
```suggestion
def verify_plug_interface(name, interface):
```

2024-08-29 07:54 UTC, baconYao commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/check_gadget_interface.py
> +        varify_plug_interface(args.name, args.interface)
```suggestion
        verify_plug_interface(args.name, args.interface)
```

2024-08-29 07:54 UTC, baconYao commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/bin/check_gadget_interface.py
> +        varify_slot_interface(args.name, args.interface)
```suggestion
        verify_slot_interface(args.name, args.interface)
```

2024-08-30 01:51 UTC, stanley31huang commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
> +    Usage
```suggestion
```

2024-08-30 01:52 UTC, stanley31huang commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
> +    Usage
remove unused description

2024-08-30 01:53 UTC, stanley31huang commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
> +    Usage
removed it

2024-08-30 01:53 UTC, stanley31huang commented on contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/gadget/jobs.pxu
> +    Usage
```suggestion
```

2024-09-02 06:11 UTC, baconYao approved these changes
LGTM

2024-09-02 08:12 UTC, merged