Report invalid units generated during test session (bugfix)
canonical/checkbox pull request #1560
Opened 2024-10-23 15:52 UTC by Hook25

## Description

Currently if a template generates a unit that is invalid, a message is logged (error for some, debug for some others) and the unit is skipped. This message is visible using Checkbox local but it burried in the Agent log in remote. This is of course sub-optimal as we have no recollection of anything happening after the fact but this can lead to tests being... not executed, without an explanation or even a way for the user to notice. 

This PR moves the validation at `run_job` time, reporting the failure to the user with a clear text when the job would be executed with an explanation as to why the job wasn't executed. This also marks the job as failed (and the test run as failed), making the failure easier to find and to audit. 

## Resolved issues

Fixes: https://warthogs.atlassian.net/browse/CHECKBOX-1629

## Documentation

Pending implementation approval, I think this should be mentioned in both the extended tutorial and the normal tutorial

## Tests

This implements a new metabox scenario

2024-12-10 15:41 UTC, pieqq requested changes
Great stuff!

A few typos and other small comments, but otherwise good to land I think!

2024-12-10 15:41 UTC, pieqq commented on checkbox-ng/plainbox/impl/unit/test_unit.py
> +            #       it is a tempalte, but the definition is in Unit, not
```suggestion
            #       it is a template, but the definition is in Unit, not
```

2024-12-11 14:48 UTC, Hook25 commented on checkbox-ng/plainbox/impl/config.py
> +                "Units generated by templates can crash Checkbox when invalid or "
Fixed

2024-12-11 14:48 UTC, Hook25 commented on checkbox-ng/plainbox/impl/config.py
> +                "be reported as invalid",
Improved the description, see if makes sense

2024-12-11 15:03 UTC, pieqq approved these changes
Much clearer, thanks!

2024-12-11 15:45 UTC, merged