Fix netplan config uc16 (BugFix)
canonical/checkbox pull request #1598
Opened 2024-11-12 16:46 UTC by fernando79513

## Description

Wireless tests started failing for ubuntu core 16 after a change in Checkbox was introduced to use a different netplan config. The auth field was added to the netplan config, which seems to be incompatible with the Ubuntu Core 16 netplan config.

We are now checking the ubuntu version and using the old configuration for ubuntu 16.

## Resolved issues

[CHECKBOX-1611](https://warthogs.atlassian.net/browse/CHECKBOX-1611)
#1538 

## Documentation

## Tests

Test run of the netplan tests in one of the failing devices using ubuntu core 16:
https://certification.canonical.com/hardware/201811-26649/submission/401743/

[CHECKBOX-1611]: https://warthogs.atlassian.net/browse/CHECKBOX-1611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-14 08:34 UTC, andrejvelichkovski approved these changes
The changes look good! Thanks a lot for fixing this issue!

2024-11-14 10:54 UTC, fernando79513 commented on providers/base/bin/wifi_client_test_netplan.py
> +        if ubuntu_version and "16" in ubuntu_version:
Yes, I tested it also on raspi3 and it was "16" instead of "16.04"

2024-11-14 12:01 UTC, pieqq requested changes
Looks OK, but I would suggest to move the convenience function to get Ubuntu version to checkbox-support.

2024-11-14 12:01 UTC, pieqq commented on providers/base/bin/wifi_client_test_netplan.py
> +def get_ubuntu_version():
This should live in Checkbox support, not in an independent test script.

Python comes with some support for this in the stdlib (in the [`platform` module](https://docs.python.org/3/library/platform.html)), but it's inconsistent between Python versions unfortunately...

2024-11-15 15:09 UTC, pieqq approved these changes
LGTM!

2024-11-15 15:26 UTC, merged