Add AMD PMF driver loading validation (New)
canonical/checkbox pull request #1620
Opened 2024-11-26 04:02 UTC by hanhsuan

## Description

[AMD PMF](https://www.phoronix.com/news/AMD-PMF-Linux-Driver) (Platform Management Framework) is a new feature that required by client to validate.
Currently, the test plan is only included one loading test, and will be enhanced in the future.

## Resolved issues

[Internal Jira ticket](https://warthogs.atlassian.net/browse/DELTA-21)

## Documentation

## Tests

manifest false to skip: https://certification.canonical.com/hardware/202001-27667/submission/403122/
AMD PMF isn't  loaded: https://certification.canonical.com/hardware/202001-27667/submission/403120/
AMD PMF is loaded: https://certification.canonical.com/hardware/202401-33431/submission/403125/

2024-12-19 16:06 UTC, pieqq requested changes
Hello! Sorry for the late review...

Please check my inline comments and see if they make sense.

2024-12-20 07:18 UTC, hanhsuan commented on providers/base/bin/amd_pmf.py
> +class AMDPMF:
I thought that there will be more test cases for AMD PMF driver. Therefore, I would like to use class to make it could add more function.

2025-02-14 10:57 UTC, pieqq requested changes

2025-02-14 10:57 UTC, pieqq commented on providers/base/bin/amd_pmf.py
> +class AMDPMF:
I still think it's better to keep things simple. You can always revisit this in the future when you have other use cases that do require a class (but maybe separate functions will be OK too!).

By removing the class, you don't need to instantiate it in the main function.

2025-02-21 09:39 UTC, pieqq approved these changes
LGTM, thanks!

2025-02-26 08:10 UTC, merged