Add: new manifest for touchpad
canonical/checkbox pull request #293
Opened 2023-01-06 01:30 UTC by baconYao

The original jobs appear and be executed based on the Chassis type from DMI information. However, there are more and more IoT devices which don't equip the physical touchpad nowadays. And for some reasons, their Chassis type matchs the condition of the touchpad job, this causes those touchpad jobs will be executed but tester need to skip them manually.

Therefore, the manifest of touchpad will bring a huge benefit for us to filter jobs out in advanced.

I add the has_touchpad manifest option and apply it to all of the touchpad jobs.

## Description

Describe your changes here:

- What's the problem solved (briefly, since the issue is where this is elaborated in more detail).
- Introduce your implementation approach in a way that helps reviewing it well.

## Resolved issues

Note the Jira/Launchpad issue(s) resolved by this PR (`Fixes|Resolves ...`).

## Documentation

- [ ] Automated tests are included for the changed functionality in this PR. If to be merged without tests, please elaborate why.
- [ ] Necessary documentation is provided for the changed functionality in this PR (tests are documentation, too).

## Tests

- [ ] Steps to follow for reviewer to run & manually test are provided.
- [ ] A list of what tests were run and on what platform/configuration is provided.

2023-01-06 09:42 UTC, yphus requested changes
Adding a new manifest entry is a good idea. It will be prompted by checkbox for all test plans using one of the [touchpad nested test plans](https://github.com/canonical/checkbox/blob/main/providers/base/units/touchpad/test-plan.pxu) though. Then I don't think keeping requirements like `dmi.product in ['Notebook','Laptop','Portable','Convertible']` is necessary.

2023-01-10 02:37 UTC, baconYao commented
@yphus I agree your viewpoint. I can remove the dmi checking and resubmit code once cert team has conclusion.

2023-01-12 00:35 UTC, baconYao commented
@yphus I've removed the dmi.production requirement. Please help to review it again. Many thanks.

2023-01-13 06:29 UTC, pieqq commented
Looks good to me. Thanks a lot @baconYao !

2023-01-13 06:30 UTC, merged