Using also-after-suspend flag to keep test consistency before and after suspend for 22.04 automated test plan
canonical/checkbox pull request #306
Opened 2023-01-19 04:47 UTC by weizhenwu

## Description

To make sure we test extact same cases before and after suspend, I've made following change:
1. Use flag: also-after-suspend for all test cases
2. Modify desktop automated test plan to use after-suspend test instead of suspend/

for some log attached test cases, I create a new one with prefix after-suspend instead of using flag: also-after-suspend because the log file will be replaced

## Resolved issues

None

## Documentation

- [ ] Automated tests are included for the changed functionality in this PR. If to be merged without tests, please elaborate why.
- [ ] Necessary documentation is provided for the changed functionality in this PR (tests are documentation, too).

## Tests

$ checkbox-cli list-bootstrapped com.canonical.certification::client-cert-desktop-22-04-automated
https://pastebin.canonical.com/p/nvnNJn6RZp/

2023-01-19 09:59 UTC, pieqq requested changes
I just did a quick pass and noticed a typo.

Also, it would be good if you could include a `checkbox-cli list-bootstrapped` before the change and after, so that we can compare easily to make sure jobs that should be replaced are, indeed, getting replaced :)

2023-01-19 09:59 UTC, pieqq commented on providers/base/units/camera/test-plan.pxu
> +id: aftre-suspend-camera-cert-automated
typo: it should be `after-suspend-camera-cert-automated`.

2023-01-19 09:59 UTC, pieqq commented on providers/base/units/camera/test-plan.pxu
> + aftre-suspend-camera/multiple-resolution-images_.*              certification-status=blocker
typo in the last two lines, should be `after-suspend...`

2023-01-19 09:59 UTC, pieqq commented on providers/certification-client/units/client-cert-desktop-22-04.pxu
> +    aftre-suspend-camera-cert-automated
Typo: `aftre`.

2023-02-06 09:19 UTC, weizhenwu commented
> Thanks!
> 
> I just did a quick pass and noticed a typo.
> 
> Also, it would be good if you could include a `checkbox-cli list-bootstrapped` before the change and after, so that we can compare easily to make sure jobs that should be replaced are, indeed, getting replaced :)

Thanks for reviewing!
I've fix the typo and pasted the link of list-bootstrapped output before applying the change.

2023-03-02 10:23 UTC, yphus commented
Please rebase your work on top of current main branch

2023-03-09 02:41 UTC, merged