Remove apste_support_on_.* from Server Certification disk tests
canonical/checkbox pull request #315
Opened 2023-01-26 19:10 UTC by rodwsmith

## Description

Describe your changes here:

Removed apste_support_on_.* from Server Certification disk tests

## Resolved issues

https://warthogs.atlassian.net/browse/SERVCERT-455

## Documentation

- [ ] Automated tests are included for the changed functionality in this PR. If to be merged without tests, please elaborate why.
- [ ] Necessary documentation is provided for the changed functionality in this PR (tests are documentation, too).

## Tests

- [ ] Steps to follow for reviewer to run & manually test are provided.
- [ ] A list of what tests were run and on what platform/configuration is provided.

2023-01-27 16:58 UTC, bladernr commented on providers/base/units/disk/test-plan.pxu
> -    disk/apste_support_on_.*                   certification-status=non-blocker
Please verify this is not in use by the devices team (I don't think we use any of the test plans marked as "manual"

2023-01-27 17:09 UTC, bladernr requested changes
Trying an inline comment... haven't done that on Git yet...
tl;dr - the removal from disk-cert-automated should be reverted, while keeping the removal from server-disk

2023-01-27 17:09 UTC, bladernr commented on providers/base/units/disk/test-plan.pxu
> -    disk/apste_support_on_.*
This one should not be removed, this is the automated disk test plan that Devices uses, the test is OK for them as APSTE is a feature on consumer grade devices, while not being a feature on enterprise grade devices.

2023-01-27 20:15 UTC, bladernr requested changes
Sorry to do this, but could you squash these two commits into a single one? rather than logging two commits where the second just reverses something in the first one, it's cleaner to just squash and push a single commit.  It's pedantic, I know, but keeps the history a bit cleaner.

2023-01-30 17:12 UTC, rodwsmith commented
> Sorry to do this, but could you squash these two commits into a single one? rather than logging two commits where the second just reverses something in the first one, it's cleaner to just squash and push a single commit. It's pedantic, I know, but keeps the history a bit cleaner.

Done.

2023-01-30 18:01 UTC, bladernr approved these changes

2023-01-30 18:06 UTC, bladernr requested changes
OK, one more thing I missed... sorry, also part of this is me learning how to review things on Github.  But you're missing an underscore where you restored this in the devices test plan.  That'll cause their tests to potentially break since the name is slightly different than expected.

2023-01-30 18:42 UTC, rodwsmith commented
> 

This time git blew up in my face when I tried to squash my changes, so I'm closing this PR and have opened a new one: https://github.com/canonical/checkbox/pull/319

2023-01-30 18:42 UTC, closed without merging