Integrate Metabox in the Github workflow
canonical/checkbox pull request #355
Opened 2023-03-08 08:43 UTC by pieqq

## Description

Create a GitHub action to run Metabox on a variety of configs (Checkbox local, remote, Ubuntu 18.04/20.04/22.04) when a PR is approved.

## Resolved issues

CHECKBOX-451

2023-03-08 17:27 UTC, yphus requested changes
with `runs-on: ubuntu-20.04` you can have a config for 16.04 (no cgroups issues with a host running 20.04)

2023-03-09 01:36 UTC, pieqq commented
I've made the changes required. Hopefully we can run everything!

2023-03-09 10:48 UTC, pieqq commented
I want to amend this PR to prevent Metabox from being run if some non-Checkbox changes are approved

2023-03-09 15:18 UTC, yphus commented
> I want to amend this PR to prevent Metabox from being run if some non-Checkbox changes are approved

I've not find a way to combine both `pull_request_review` events and path filters constraints.

2023-03-10 01:35 UTC, pieqq commented
Indeed, it looks like the paths filter is only available for [`pull_request` and `pull_request_target`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore). Annoying!

Let's land it this way, then, we'll see how long it is to run.

2023-03-10 08:21 UTC, yphus requested changes
Missing 16.04 in the os matrix

2023-03-10 08:21 UTC, yphus commented on .github/workflows/metabox.yaml
> +        os: [18.04, 20.04, 22.04]
Please add 16.04 here too

2023-03-12 18:03 UTC, yphus approved these changes
LGTM

2023-03-12 18:18 UTC, yphus approved these changes
+1

2023-03-12 18:21 UTC, yphus approved these changes
+1 (after pip install --upgrade)

2023-03-13 07:44 UTC, yphus approved these changes
+1

2023-03-13 08:43 UTC, yphus approved these changes
+1

2023-03-16 08:03 UTC, merged