Improve snap building process
canonical/checkbox pull request #4
Opened 2022-10-06 11:33 UTC by kissiel

This PR rearranges the snaps' code, so:

* it's possible to build snaps for all releases
* common bits are reused
* there's no need for per-series branches

2022-10-06 11:36 UTC, kissiel commented
Some of the diffs are rendered as changing series, but that's just an artifact from git. Follow paths to see real changes.

2022-10-08 11:00 UTC, yphus requested changes
Checkbox core snaps are not using local sources, instead they keep loading parts source from launchpad:

e.g:
```
  checkbox-ng:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: https://git.launchpad.net/checkbox-ng
    source-type: git
```
must be replaced with:
```
  checkbox-ng:
    plugin: python
    source: ../../checkbox-ng
```

2022-10-08 11:01 UTC, yphus requested changes
The slots definition have to be updated to match the new provider names:

e.g:
```
slots:
  provider-resource:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-resource
  provider-checkbox:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-checkbox
```
must be replaced with:
```
slots:
  provider-resource:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-resource
  provider-checkbox:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-base
```

Warning: Do **not** change the slot name (provider-checkbox -> provider-base) in order to stay compatible with all checkbox-<project> snaps

2022-10-20 13:48 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-resource
```suggestion
      - $SNAP/providers/checkbox-provider-resource
```

2022-10-20 13:49 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-checkbox
```suggestion
      - $SNAP/providers/checkbox-provider-checkbox
```

2022-10-20 13:50 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-ipdt
```suggestion
      - $SNAP/providers/checkbox-provider-ipdt
```

2022-10-20 13:53 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-docker
```suggestion
      - $SNAP/providers/checkbox-provider-docker
```

2022-10-20 13:53 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-tpm2
```suggestion
      - $SNAP/providers/checkbox-provider-tpm2
```

2022-10-20 13:54 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-engineering-tests
```suggestion
      - $SNAP/providers/checkbox-provider-engineering-tests
```

2022-10-20 13:54 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-sru
```suggestion
      - $SNAP/providers/checkbox-provider-sru
```

2022-10-20 13:54 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-certification-client
```suggestion
      - $SNAP/providers/checkbox-provider-certification-client
```

2022-10-20 13:54 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      - $SNAP/providers/plainbox-provider-certification-server
```suggestion
      - $SNAP/providers/checkbox-provider-certification-server
```

2022-10-20 13:58 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +    source-type: git
```suggestion
  checkbox-ng:
    plugin: python
    source: checkbox-ng
    source-type: local
```

2022-10-20 14:00 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +  plainbox-provider-resource:
```suggestion
  checkbox-provider-resource:
```

2022-10-20 14:00 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-resource --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-resource --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:01 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-checkbox --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-base --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:02 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-ipdt --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-ipdt --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:03 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +    after: [plainbox-provider-checkbox]
```suggestion
    after: [checkbox-provider-base]
```

2022-10-20 14:03 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +  plainbox-provider-docker:
```suggestion
  checkbox-provider-docker:
```

2022-10-20 14:03 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-docker --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-docker --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:04 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +    after: [plainbox-provider-ipdt]
```suggestion
    after: [checkbox-provider-ipdt]
```

2022-10-20 14:04 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-tpm2 --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-tpm2 --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:04 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +    after: [plainbox-provider-docker]
```suggestion
    after: [checkbox-provider-docker]
```

2022-10-20 14:05 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +  plainbox-provider-sru:
```suggestion
  checkbox-provider-sru:
```

2022-10-20 14:05 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-sru --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-sru --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:05 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +    after: [plainbox-provider-tpm2]
```suggestion
    after: [checkbox-provider-tpm2]
```

2022-10-20 14:07 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +    after: [plainbox-provider-sru]
```suggestion
    after: [checkbox-provider-sru]
```

2022-10-20 14:07 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-gpgpu --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-gpgpu --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:07 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +  plainbox-provider-certification-client:
```suggestion
  checkbox-provider-certification-client:
```

2022-10-20 14:08 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +  plainbox-provider-certification-server:
```suggestion
  checkbox-provider-certification-server:
```

2022-10-20 14:08 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-certification-server --root="$SNAPCRAFT_PART_INSTALL"
```suggestion
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-certification-server --root="$SNAPCRAFT_PART_INSTALL"
```

2022-10-20 14:08 UTC, yphus commented on checkbox-core-snap/series16/snap/snapcraft.yaml
> +    after: [plainbox-provider-certification-server]
```suggestion
    after: [checkbox-provider-certification-server]
```

2022-10-20 14:12 UTC, yphus requested changes
Providers name have changed and all parts have to be updated to match. I've suggested edits to s16 but the same fixes are required for s18/20 and 22.

Moreover checkbox-ng and checkbox-supprt are still using lp a sources

2022-10-20 14:15 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-resource
```suggestion
    target: $SNAP/providers/checkbox-provider-resource
```

2022-10-20 14:15 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-checkbox
```suggestion
    target: $SNAP/providers/checkbox-provider-base
```

2022-10-20 14:15 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-ipdt
```suggestion
    target: $SNAP/providers/checkbox-provider-ipdt
```

2022-10-20 14:25 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-resource
```suggestion
    target: $SNAP/providers/checkbox-provider-resource
```

2022-10-20 14:25 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-checkbox
```suggestion
    target: $SNAP/providers/checkbox-provider-base
```

2022-10-20 14:26 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-ipdt
```suggestion
    target: $SNAP/providers/checkbox-provider-ipdt
```

2022-10-20 14:26 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-docker
```suggestion
    target: $SNAP/providers/checkbox-provider-docker
```

2022-10-20 14:26 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-sru
```suggestion
    target: $SNAP/providers/checkbox-provider-sru
```

2022-10-20 14:26 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-certification-client
```suggestion
    target: $SNAP/providers/checkbox-provider-certification-client
```

2022-10-20 14:27 UTC, yphus commented on checkbox-snap/series_uc22/snap/snapcraft.yaml
> +    target: $SNAP/providers/plainbox-provider-certification-server
```suggestion
    target: $SNAP/providers/checkbox-provider-certification-server
```

2022-10-20 14:29 UTC, yphus requested changes
All the checkbox snaps also can get rid of plainbox prefixes. I've suggested edits for series_uc22 but all content interfaces based snaps are impacted (uc16,18,20 and 22)

2022-10-27 22:00 UTC, kissiel commented
I applied a lot of suggested changes. I'll do more testing, but I think it's ready for another look-through.

2022-10-28 19:41 UTC, yphus commented on checkbox-core-snap/series22/snap/snapcraft.yaml
> +      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
```suggestion
      for path in $(find "$SNAPCRAFT_STAGE/../providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
```

Just for the first provider as the stage area is not yet populated; the PROVIDERPATH env var would then be empty and system providers would conflicts during a local build

2022-10-28 19:44 UTC, yphus requested changes
`s/checkbox-provider-checkbox/checkbox-provider-base/g`

Add tag versions for fwts and acpi-tools:
```
  fwts:
    source-tag: "V22.09.00"
```
[...]
```
  acpi-tools:
    source-tag: "R03_31_22"
```

2022-10-31 12:56 UTC, pieqq approved these changes
LGTM!

2022-10-31 13:16 UTC, yphus approved these changes
Thanks, LGTM too

2022-10-31 14:03 UTC, merged