Update the release README
canonical/checkbox pull request #417
Opened 2023-04-05 17:16 UTC by yphus

## Documentation

New workflows are now available to release checkbox using a unique tag.

This is the documentation update corresponding to: 
- https://github.com/canonical/checkbox/pull/402
- https://github.com/canonical/checkbox/pull/408

2023-04-06 05:51 UTC, pieqq requested changes
Thanks for providing this!

I just have some nitpicks about the form (see inline) and also the fact that it's not clear if you try to cap each line at 80 chars or not, because some paragraphs seem to be following this while others don't.

But if you don't want to make the changes, I think it's OK to land as is.

2023-04-06 05:51 UTC, pieqq commented on tools/release/README.md
> +## Bump the checkbox version
Checkbox should be uppercased to avoid confusion

2023-04-06 05:51 UTC, pieqq commented on tools/release/README.md
> +Run the [Bumpversion workflow] (the default increment is **minor**)
Missing a column at the end of the sentence, and probably a blank line between L8 and L9.

2023-04-06 05:51 UTC, pieqq commented on tools/release/README.md
> +- Run [Bumpversion] for all checkbox sub-projects, snaps and debian packages
`checkbox`, `snaps` and `debian` should be uppercased.

2023-04-06 05:51 UTC, pieqq commented on tools/release/README.md
> +[build](https://github.com/canonical/checkbox/actions/runs/4371649401/jobs/7649877336), the i386 build was blocked on an error (`Chroot problem`) for hours
Not sure if you want to cap each line at 80 characters, in which case this one has to be adapted (you can put the link at the bottom of the document, for instance).

2023-04-06 05:51 UTC, pieqq commented on tools/release/README.md
> +- snapcraft is not blocked during the snap build process. For example, in this
`snapcraft` should be uppercased.

2023-04-06 05:51 UTC, pieqq commented on tools/release/README.md
> +- the expected number of snaps are built. snapcraft
`snapcraft` should be uppercased.

2023-04-06 05:51 UTC, pieqq commented on tools/release/README.md
> +does not return 1 when only a few of the snaps are built, which leads to GHA
I would either write GitHub Actions, either use the `<abbr>` tag to explain what `GHA` means:

```
<abbr title="GitHub Actions">GHA</abbr>
```

2023-04-10 09:26 UTC, yphus commented
@pieqq thx for the sugestions, the last commit should fix them all

2023-04-10 09:58 UTC, pieqq approved these changes
All good then, thanks!

2023-04-10 09:58 UTC, merged