Add: set multiple MAC in one BTDEVADDR feature
canonical/checkbox pull request #424
Opened 2023-04-07 08:47 UTC by hanhsuan

## Description

Describe your changes here:

BTDEVADDR could not set multiple BT MAC addresses at the same time. It will make automatic testing failed, if the test BT server be occupied or not available.

The only impact job is `com.canonical.plainbox::bluetooth/bluetooth_obex_send`.

Setting of BTDEVADDR is changing from
```
BTDEVADDR = 28:3A:4D:46:79:C0
```
to
```
BTDEVADDR = 28:3A:4D:46:79:C0,7C:B2:7D:4B:14:95,34:6F:24:A8:93:EE,80:32:53:D8:0D:1E
```

## Resolved issues
- #175
- [Jira card CQT-2031](https://warthogs.atlassian.net/browse/CQT-2031)

## Documentation

- [ ] Automated tests are included for the changed functionality in this PR. If to be merged without tests, please elaborate why.
- [ ] Necessary documentation is provided for the changed functionality in this PR (tests are documentation, too).

## Tests

- [Only setting one Mac address](https://certification.canonical.com/hardware/202212-30999/submission/307865/)
- [First one Mac address could be used](https://certification.canonical.com/hardware/202212-30999/submission/307869/)
- [Latest one Mac address could be used](https://certification.canonical.com/hardware/202212-30999/submission/307868/)
- [One of the Mac address could be used](https://certification.canonical.com/hardware/202212-30999/submission/307867/)
- [All Mac address could not be used](https://certification.canonical.com/hardware/202212-30999/submission/307870/)

2023-04-07 14:24 UTC, kissiel approved these changes
Looks good. One minor English fix below.

2023-04-07 23:52 UTC, hanhsuan commented
I'm so sorry I rebased to wrong commit. Should I drop this PR then create a new one?

2023-04-08 09:35 UTC, kissiel commented
`git reset` the branch to the commit you want to keep, and repush your branch. This will delete the unwanted ones.

If there's problem with your order then you can reset your branch to the same commit as the `main` ref is pointing to and then `cherry-pick` only the commits you want to have. And then of course repush.

2023-04-10 05:02 UTC, hanhsuan commented
I have fixed it. Thanks for you help.

2023-04-10 08:54 UTC, yphus requested changes
small typo

2023-04-10 08:54 UTC, yphus commented on providers/base/units/bluetooth/jobs.pxu
> +  echo "There are no avaiable BT devices."
```suggestion
  echo "There are no available BT devices."
```

2023-04-10 09:04 UTC, hanhsuan commented on providers/base/units/bluetooth/jobs.pxu
> +  echo "There are no avaiable BT devices."
Thanks a lot. I have fixed.

2023-04-21 06:22 UTC, pieqq approved these changes
Thanks for providing a link to all the different test cases you've tested, it's really helpful!

Looks good to me.

2023-04-21 06:23 UTC, merged