Fix: Bug #443 -- better optimize network.py high-speed network
canonical/checkbox pull request #479
Opened 2023-05-19 19:02 UTC by rodwsmith

Fix: Bug #443 -- better optimize network.py high-speed network performance.

## Description

## Resolved issues

## Documentation

## Tests

2023-05-23 18:05 UTC, bladernr commented on providers/base/bin/network.py
> +            node_num = int(file.read())
This would be a bit cleaner using with:
try:
  with open(filename, "r") as file:
    node_num = int(file.read())
except FileNotFoundError

2023-05-23 18:08 UTC, bladernr commented on providers/base/bin/network.py
> +        except FileNotFoundError:
I just realized that FileNotFoundError is referred to a couple times, but is not imported. The script also traps CalledProcessError directly, but that IS explicitly imported.

2023-05-23 18:55 UTC, bladernr requested changes
minor point about using with when opening filename so that the file is properly closed, otherwise LGTM. I think this is going to be a bit noisy (I haven't run it yet to see) so we likely will want to revisit this next cycle and clean up the output a bit in general.

2023-05-24 17:47 UTC, rodwsmith commented
I've made Jeff's suggested changes and squashed the results.

Also, I've changed the description (shown near the top of this page, at least to me). I accidentally left the whole thing commented out on the original submission; I've fixed that mistake. Note that the description includes a sample output from running the revised script. The PR includes code to disable logging when doing the test runs, but adds summaries for each test run. This minimizes the added clutter, but there IS some extra output, to help in case there are problems when this type of output might be helpful.

Finally, I've also created a PR for minor changes to the STG so that users know to launch more instances of iperf3 on the Target system:

https://github.com/canonical/certification-docs/pull/17

2023-05-24 18:09 UTC, bladernr approved these changes
Cool, Thanks!

2023-05-30 06:15 UTC, merged

2023-06-07 02:05 UTC, baconYao commented
Hi @pieqq and @rodwsmith

Test environment:
- Device: Raspberry PI 4
- OS: Desktop image (I downloaded it from the [Ubuntu Official Website](https://ubuntu.com/download/raspberry-pi/thank-you?version=22.04.2&architecture=desktop-arm64+raspi))
- Snap:
  ```
   u@u-desktop:~$ snap list
   Name                       Version           Rev    Tracking         Publisher            Notes
   checkbox                   2.6               2418   latest/stable    ce-certification-qa  classic
   checkbox22                 2.6               372    latest/stable    ce-certification-qa  -
  ```

### I ran into a problem which gives the error like below

```
-----------------------[ Iperf3 stress testing for eth0 ]-----------------------
ID: com.canonical.certification::ethernet/iperf3_eth0
Category: Ethernet Device tests
--------------------------------------------------------------------------------
INFO:root:Testing eth0 against 10.102.88.220
INFO:root:Have successfully pinged 10.102.88.220 on eth0
INFO:root:-------------------- Test Run Number 1 --------------------
INFO:root:Using 1 thread.
WARNING:root:WARNING: Could not find the NUMA node associated with eth0!
WARNING:root:Setting the association to NUMA node 0, which may not be optimal!
INFO:root:NUMA node of eth0 is 0....
Traceback (most recent call last):
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 1023, in <module>
    sys.exit(main())
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 1019, in main
    return args.func(args)
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 783, in interface_test
    error_number = run_test(args, test_target)
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 614, in run_test
    error_number = iperf_benchmark.run()
  File "/tmp/nest-pmj_1dlm.733188759a536d454588eb1b832197fe0ac6141c07b5ee7f5b36d7837164df28/network.py", line 292, in run
    core = core_list[thread_num % len(core_list)]
ZeroDivisionError: integer division or modulo by zero
--------------------------------------------------------------------------------
Outcome: job failed
```

### What happened?

According this PR, it tries to find the number of NUMA node via `lscpu` command, however, there is no NUMA node on RPI 4. This result causes the problem above.

```
u@u-desktop:/sys/class/net/eth0/device$ lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p3
    CPU max MHz:         1800.0000
    CPU min MHz:         600.0000
    BogoMIPS:            108.00
    Flags:               fp asimd evtstrm crc32 cpuid
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   192 KiB (4 instances)
  L2:                    1 MiB (1 instance)
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

```
u@u-desktop:/sys/class/net/eth0/device$ ls -al
total 0
drwxr-xr-x  5 root root    0  一   1  1970 .
drwxr-xr-x 10 root root    0  一   1  1970 ..
lrwxrwxrwx  1 root root    0  一   1  1970 driver -> ../../../../bus/platform/drivers/bcmgenet
-rw-r--r--  1 root root 4096  六   7 09:45 driver_override
-r--r--r--  1 root root 4096  六   7 09:45 modalias
drwxr-xr-x  3 root root    0  一   1  1970 net
lrwxrwxrwx  1 root root    0  六   7 09:45 of_node -> ../../../../firmware/devicetree/base/scb/ethernet@7d580000
drwxr-xr-x  2 root root    0  六   7 09:45 power
lrwxrwxrwx  1 root root    0  一   1  1970 subsystem -> ../../../../bus/platform
-rw-r--r--  1 root root 4096  一   1  1970 uevent
drwxr-xr-x  4 root root    0  一   1  1970 unimac-mdio.-19
```

2023-06-08 06:38 UTC, baconYao commented
> @baconYao , could you please file a bug report? It looks like this should be easy enough to fix, but it would be helpful to have a bug report to reference in the PR. I don't have an RPi 4, but I do have an earlier version, so I can try testing on it.

Hi @rodwsmith, I file an issue #539.