Show values of GROUP argument for list command help
canonical/checkbox pull request #496
Opened 2023-05-24 15:04 UTC by petitfou

It can be helpful to have the list of all possible values for GROUP argument

## Description

## Resolved issues

## Documentation

## Tests

Manual test done

2023-05-24 16:59 UTC, kissiel requested changes
There are also "special" group - `all-jobs`. It would be killed with this patch, and I think the feature is still useful to people. I think the easiest way to handle that is just simply adding `all-jobs` to choices here.

2023-05-24 17:25 UTC, petitfou commented
> There are also "special" group - `all-jobs`. It would be killed with this patch, and I think the feature is still useful to people. I think the easiest way to handle that is just simply adding `all-jobs` to choices here.

nice catch, thanks

2023-05-24 17:45 UTC, kissiel approved these changes
TYVM! +1

2023-05-30 06:20 UTC, pieqq approved these changes
+1. Thanks for this QoL improvement!

2023-05-30 06:20 UTC, merged