refactor: checkbox configs
canonical/checkbox pull request #519
Opened 2023-05-31 08:39 UTC by kissiel

## Description

Instead of relying on a fairly baroque approach to storing and merging configs, this patch introduces a simpler way of handling those.

The idea is that when the config object is created, it is filled with default values and it's getting updated with new values coming from other configs, launchers, and potentially a session-only values (with urwid screen in checkbox ui).

This patch also makes checkbox track the origins of those values to help test authors, developers, and operators inspect testing setup.

The `check-config` subcommand now prints the origins as well.

This patch gets rid of the magical `Unset` value from configs in favor of normal python types.

## Resolved issues

## Documentation

The config functionality is kept.

## Tests

Unit tests are included in the branch and metabox helped shape this branch, as they cover configs extensively.

2023-05-31 13:31 UTC, Hook25 requested changes
I have a few minor points but overall very nice refactoring! Thanks

As a side, sort of related comment, we should consider launching `black` on every python file in the repo and then automatically integrate it in our workflow because else it will baloon diffs like it did here. I like it a lot and leaves the code easier to read but makes reviewing harder like it did here if it is not used systemically

2023-06-13 20:55 UTC, kissiel commented on checkbox-ng/checkbox_ng/config.py
> +def load_configs(launcher_file=None, cfg=None):
Fixed in your 913c926aa :D

2023-06-13 20:55 UTC, kissiel commented on checkbox-ng/checkbox_ng/config.py
> +    ]
Fixed in 9ec966214

2023-06-13 20:56 UTC, kissiel commented on checkbox-ng/checkbox_ng/config.py
> +            'config file: {}'.format(previous_cfg_name))
Fixed in your 913c926aa :D

2023-06-13 20:56 UTC, kissiel commented on checkbox-ng/checkbox_ng/config.py
> +            'Launcher file: {}'.format(launcher_file))
Fixed in your 913c926aa :D

2023-06-13 20:58 UTC, kissiel commented on checkbox-ng/checkbox_ng/launcher/checkbox_cli.py
> +            )
Fixed in 9ec966214

2023-06-13 21:02 UTC, kissiel commented on checkbox-ng/checkbox_ng/launcher/stages.py
> +            """
Fixed in 9ec966214

2023-06-13 21:02 UTC, kissiel commented on checkbox-ng/checkbox_ng/launcher/stages.py
> +                        "transport:c3" not in self.sa.config.sections.keys()
Fixed in 9ec966214

2023-06-13 21:03 UTC, kissiel commented on checkbox-ng/checkbox_ng/launcher/stages.py
> +                        _(
Fixed in 9ec966214

2023-06-13 21:03 UTC, kissiel commented on checkbox-ng/plainbox/impl/config.py
> +                    if ':' in section and section not in self.sections.keys():
Fixed in 9ec966214

2023-06-13 21:11 UTC, kissiel commented on checkbox-ng/checkbox_ng/launcher/subcommands.py
> +        # (launcher path) is optional
Fixed in b46788b44

2023-06-13 21:20 UTC, kissiel commented on checkbox-ng/plainbox/impl/config.py
> +            pass
I agree with both ideas.
Here's third: this outlined function could return the prefix if parametrized and None otherwise.
WDYT?

2023-06-14 08:12 UTC, kissiel commented on checkbox-ng/plainbox/impl/config.py
> +            raise ValueError("No such section in the spec ({}".format(prefix))
Fixed in a2e95b64c

2023-06-14 08:12 UTC, kissiel commented on checkbox-ng/plainbox/impl/config.py
> +            if isinstance(contents, ParametricSection):
Fixed in a2e95b64c

2023-06-14 08:17 UTC, kissiel commented on checkbox-ng/plainbox/impl/session/remote_assistant.py
> +                launcher_from_controller, "Remote launcher")
Probably, but I'd do it in a separate PR.

2023-06-14 10:12 UTC, kissiel commented on checkbox-ng/plainbox/impl/config.py
> +            raise ValueError("No such section in the spec ({}".format(prefix))
Actually the logic is opposite, we're looking for the param section.

2023-06-14 10:15 UTC, kissiel commented on checkbox-ng/plainbox/impl/config.py
> +            raise ValueError("No such section in the spec ({}".format(prefix))
Fixed in 720ffa9d8

2023-06-14 12:04 UTC, Hook25 approved these changes
+1 very nice change
TYVM :)

2023-06-14 12:06 UTC, merged