Exclude the debian directory from source dist and wheel packages
canonical/checkbox pull request #608
Opened 2023-07-05 13:33 UTC by yphus

## Description

Python wheel packagse created using the python build module include the debian packaging subdir

## Resolved issues

checkbox core snap builds are failing to stage checkbox-ng and checkbox-support since they both copied their respective debian subdir to the staging location.

## Documentation

N/A

## Tests

Tested both chgeckbox-ng and checkbox-support wheel packages, they don't include debian dirs:

`python3 -m build --no-isolation --wheel --outdir /tmp/`

2023-07-05 14:39 UTC, Hook25 requested changes
The other pr has landed in main, rebasing this branch and building series20 will still produce this error if the `rm -f` bodge is removed from the recipe for series20
```
Failed to stage: Parts 'checkbox-support' and 'checkbox-ng' have the following files, but with different contents:
    lib/python3.8/site-packages/debian/changelog
    lib/python3.8/site-packages/debian/compat
    lib/python3.8/site-packages/debian/control
    lib/python3.8/site-packages/debian/copyright
    lib/python3.8/site-packages/debian/rules

Snapcraft offers some capabilities to solve this by use of the following keywords:
    - `filesets`
    - `stage`
    - `snap`
    - `organize`

To learn more about these part keywords, run `snapcraft help plugins`.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

2023-07-06 08:14 UTC, yphus commented
I've tested the `pip3 wheel --no-deps -wheel-dir=/tmp .` command with new exclude filters this time provided in the pyproject.toml. 

Here's a diff from the two versions:

```
< Archive:  checkbox_ng-2.9.dev31+g9f71ba08e-py3-none-any.whl
---
> Archive:  checkbox_ng-2.9.dev31+g9f71ba08e.d20230706-py3-none-any.whl
37,48d36
<      5949  2023-07-06 07:57   debian/changelog
<        88  2023-07-06 07:57   debian/checkbox-ng.install
<       143  2023-07-06 07:57   debian/checkbox-ng.lintian-overrides
<       280  2023-07-06 07:57   debian/checkbox-ng.service
<       126  2023-07-06 07:57   debian/com.canonical.certification.checkbox.pkla
<         3  2023-07-06 07:57   debian/compat
<      2788  2023-07-06 07:57   debian/control
<      4848  2023-07-06 07:57   debian/copyright
<       346  2023-07-06 07:57   debian/python3-checkbox-ng.links
<      1327  2023-07-06 07:57   debian/python3-checkbox-ng.preinst
<      1603  2023-07-06 07:57   debian/rules
<        13  2023-07-06 07:57   debian/source/format
```

2023-07-06 09:42 UTC, Hook25 requested changes
This does not solve the snapcraft build yet, if I remove the `rm -f` hack I get:
```
Failed to stage: Parts 'checkbox-support' and 'checkbox-ng' have the following files, but with different contents:
    lib/python3.8/site-packages/debian/changelog
    lib/python3.8/site-packages/debian/compat
    lib/python3.8/site-packages/debian/control
    lib/python3.8/site-packages/debian/copyright
    lib/python3.8/site-packages/debian/rules

Snapcraft offers some capabilities to solve this by use of the following keywords:
    - `filesets`
    - `stage`
    - `snap`
    - `organize`
```

2023-07-07 17:56 UTC, yphus commented
Use a cleaner snapcraft syntax to remove the debian folders from the staging area

2023-07-11 09:36 UTC, Hook25 approved these changes
This works and is way better than my bodge! Sad that we have to manually exclude that dir, I think its the pip version that is not compliant to the ignore directive

2023-07-12 06:45 UTC, merged