add the canary test plan
canonical/checkbox pull request #674
Opened 2023-08-21 22:04 UTC by kissiel

## Description

 This test plan is meant to run on Checkbox versions that are candidates for
 a release. The jobs included here are explicitly listed so the same jobs are
 run in each session. Moreover, the jobs picked here are ones that on a stable
 device should all pass if the Checkbox stack is ok. In other words, failure
 to successfully run all the tests contained here should signify that there is
 a bug in the Checkbox code.

## Resolved issues
Resolves [CHECKBOX-795](https://warthogs.atlassian.net/browse/CHECKBOX-795)

2023-08-22 02:11 UTC, pieqq requested changes
This test plan looks good. It covers:

- normal jobs
- template jobs
- template jobs using the jinja2 engine
- different kinds of reboot
- suspend/resume
- after-suspend jobs

It doesn't have any graphics-related job though; how about adding `graphics/{index}_driver_version_{product_slug}` (it's a before and after suspend job that spits out some driver info)? It would requires `graphics_card` resource job.

I also have a question inline.

2023-08-22 06:56 UTC, kissiel commented on providers/base/units/canary/canary.pxu
> + com.canonical.certification::power-management/post-cold-reboot
That's my mistake stemming from the approach I took to generate the list. Removed in 604108b27a9a2418cdc656f32582a1f18dd533b7

2023-08-22 06:57 UTC, kissiel commented
> It doesn't have any graphics-related job though; how about adding `graphics/{index}_driver_version_{product_slug}` (it's a before and after suspend job that spits out some driver info)? It would requires `graphics_card` resource job.

Great idea. So here goes your first addition compared to what we had previously for edge testing (as it used IoT TP, so no GPU stuff). Added in d30661e1f4b3ed286dd726c77f100f0fcf6492d4.

2023-08-24 01:38 UTC, pieqq approved these changes
All good, thanks!

2023-08-24 01:39 UTC, merged