Update the Virtualization Test to  Clean up Logs
canonical/checkbox pull request #743
Opened 2023-09-21 20:09 UTC by mreed8855

I have added an option to reduce the error messages shown in the logs while the script checks to see if the virtual machine has booted. (Bugfix) 

This fixes this issue
https://github.com/canonical/checkbox/issues/695

Jira Card
https://warthogs.atlassian.net/browse/SERVCERT-1259

This PR will replace  PR https://github.com/canonical/checkbox/pull/720

## Description

## Resolved issues
https://github.com/canonical/checkbox/issues/695

## Documentation

## Tests
Run checkbox and run the virtualization/verify_lxd_vm job

2023-09-22 07:50 UTC, Hook25 requested changes
I have suggested a couple of ideas here and there, overall nice contribution, thank you.

To consider this ready I will need to ask you to write a few unit tests to improve the overall [coverage of this contribution](https://github.com/canonical/checkbox/blob/main/CONTRIBUTING.md#coverage). Given that we have a 90% target on patches, covering `cleanup` and `run_command` should be enough but if you want/can, try to reach 100% (covering `start_vm` is going to be a little bit more complicated but we really need to improve the overall coverage of provider scripts and checkbox itself!).

2023-09-22 07:50 UTC, Hook25 commented on providers/base/bin/virtualization.py
> +    def run_command(self, cmd, error_msgs=True):
I would change this parameter to `log_stderr` because it avoids the `logger.error` call but also the `logger.debug` further below

2023-09-22 07:50 UTC, Hook25 commented on providers/base/bin/virtualization.py
>              logging.error(' STDOUT: {}'.format(task.stdout))
Minor: maybe we want the same pattern as below? `if task.stdout: ...`

2023-09-22 07:50 UTC, Hook25 commented on providers/base/bin/virtualization.py
> +            elif task.stderr != '' and error_msgs:
this `elif` is a bit weird, a task may have both `stdout and stderr`. I would change this to:
```python
if task.stdout:
  logging.debug(' STDOUT: {}'.format(task.stdout))
if task.stderr and error_msgs: # <- if you change the name, change it here as well
  logging.debug(' STDERR: {}'.format(task.stderr))
if not (task.stderr or task.stdout): 
  # we could be smart here and do elif not task.stdout
  # but I think this is a bit cleaner
  logging.debug(' Command returned no output')
```

Minor: `if string_var != ''` == `if string_var`

2023-09-22 07:50 UTC, Hook25 commented on providers/base/bin/virtualization.py
> +        self.run_command('lxc delete --force {}'.format(self.name), False)
Minor and possibly out of the scope of this PR: it is a very strange behavior to use strings everywhere and then split them with `shlex.split`, this should be changed in the future to use arrays everywhere IMO

2024-01-10 10:29 UTC, kissiel approved these changes
Awesome, +1

2024-01-10 10:49 UTC, merged