Introduce refresh/revert tests for kernel/snapd/gadget snaps (New)
canonical/checkbox pull request #805
Opened 2023-10-30 08:41 UTC by pieqq

This branch is exactly the same as the one used for #724, but with a different name in order not to break the runners policy. Please check #724 for explanation, how to test, all the previous comments addressed, etc.

-->
## Description

## Resolved issues

[CHECKBOX-717](https://warthogs.atlassian.net/browse/CHECKBOX-717)

## Documentation

## Tests

2023-11-02 02:08 UTC, pieqq commented
I run the `com.canonical.certification::ubuntucore-snap-refresh-revert` test plan on the target device in the lab: https://certification.canonical.com/hardware/202207-30448/submission/341140/

Results are as expected:

- `snapd` (beta revision 20515) was refreshed/reverted to and from the base rev (19267) and the stable rev (20290) :heavy_check_mark: 
- `pc-kernel` (beta revision 1466) was refresh/reverted to and from the base rev (1289) but not the stable rev since it's the same as beta rev (1466) :heavy_check_mark: 
- `xinyi-pc-classic` (gadget snap, beta revision 18) was not refreshed/reverted from neither base nor stable since all of the tracks point to the same revision (18) xinyi-pc-classic

2023-11-02 07:51 UTC, Hook25 requested changes
I have a couple of notes about tests and possibly a missing arg. Overall a nice contributin. If the old PR is superseeded by this one, please close it.

2023-11-03 02:56 UTC, pieqq commented on providers/base/tests/test_snap_update_test.py
> +        logging.disable(logging.CRITICAL)
I tried mocking `snap_update_test.logging` by patching it for the affected test methods, but the logs are still showing up when running the tests.

In the end, I went for the `setUpClass/tearDownClass` way to disable and re-enable logging.

2023-11-03 03:12 UTC, pieqq commented on providers/base/bin/snap_update_test.py
> +                        )
Done.

2023-11-03 03:12 UTC, pieqq commented on providers/base/tests/test_snap_update_test.py
> +        assert mock_stdout.getvalue().endswith("\n\n")
Done

2023-11-03 03:15 UTC, pieqq commented on providers/base/tests/test_snap_update_test.py
> +        self.assertTrue(snap_update_test.save_change_info.called)
I modified this test to check that the `Snapd.refresh()` method was called. In my previous implementation, the `mock_self` object passed to `snap_update_test.SnapRefreshRevert.snap_refresh` did not actually initialized `self.snapd` to `Snapd()`, so I added that to be able to check that the `refresh()` method was called.

2023-11-03 03:15 UTC, pieqq commented on providers/base/tests/test_snap_update_test.py
> +        mock_self.snap_info = mock_snap_info
Done.

2023-11-06 03:19 UTC, pieqq commented on providers/base/bin/snap_update_test.py
> +            raise SystemExit()
Good catch! Fixed in fd02e6f68a785947abaf62856249a69f98b638d9

2023-11-06 08:28 UTC, Hook25 approved these changes
+1, TY for the patience!

2023-11-06 09:30 UTC, merged