Improve warn message for skipped file at provider loading
canonical/checkbox pull request #814
Opened 2023-11-06 19:44 UTC by alexandredosim

The warn message informs about the file being skipped without the reason it happens. This will add that the file is not executable (hence will be skipped).

2023-11-07 08:27 UTC, Hook25 commented
Hello, thank you for your contribution. Sadly that function is untested, and that makes codecov unhappy. Are you able to write a small test that checks that the function logs when it should?

2023-11-07 17:28 UTC, alexandredosim commented
> Hello, thank you for your contribution. Sadly that function is untested, and that makes codecov unhappy. Are you able to write a small test that checks that the function logs when it should?

Since I didn't implemented the function, I thought that tests wouldn't be necessary, I'm sorry.
Can I implement the tests with pytest? When I finish then, what do I do to include them on this PR? Unit tests are sufficient or I need to implement integration tests too?
Thanks

2023-11-08 10:04 UTC, Hook25 commented
You can add a test in the `test_v1`test, use unittest and yes, just write a unit test for that specific function.

2023-11-13 21:01 UTC, alexandredosim commented
I'm sorry for my noob git abilities. Do I need to rebase every time I want to push the commits?
As one can see, I took the freedom to refactor the `_warn_warn_ignored_file` function. I hope this is useful.

2023-11-15 10:49 UTC, Hook25 requested changes
We usually rebase the branch before landing on the state of our origin (I suppose you have more than 1 remote in your local repo). Here something went wrong, I don't know exactly what you did but the changes shown in this PR are more than they should be. Did you merge/rebase on a wrong commit? 

You can fix this by rebasing on the correct commit and (if you merged main in manually), rolling the merge back. If you need more support on this feel free to reach out.

I have the last few comments about your tests (and refactor). Minor things here and there, ty for writing the tests, it really helps us out quite a lot.

2023-11-15 10:49 UTC, Hook25 commented on checkbox-ng/plainbox/impl/secure/providers/test_v1.py
> +        ]
Change this to `os.path.join`

2023-11-15 10:49 UTC, Hook25 commented on checkbox-ng/plainbox/impl/secure/providers/test_v1.py
> +        filename = '/'.join([self.units_path, 'unitsfile'])
`os.path.join`

2023-11-15 10:49 UTC, Hook25 commented on checkbox-ng/plainbox/impl/secure/providers/test_v1.py
> +            self.assertRegex(log_recorder.output[0], '(?i)skip')
```python
            self.assertIn(filename, log_recorder.output[0])
            self.assertIn('executable', log_recorder.output[0])
            self.assertIn('skip', log_recorder.output[0])
```

2023-11-15 10:49 UTC, Hook25 commented on checkbox-ng/plainbox/impl/secure/providers/v1.py
> +            logger.warning("File %s is not executable, skipping", filename)
The old code was indeed not super clear. I would write it this way:

```python
provider_folders = [
    self.provider.units_dir, 
    self.provider.jobs_dir, 
    self.provider.data_dir, 
    self.provider.bin_dir, 
    self.provider.locale_dir
]
if any(location and filename.startswith(location) for location in provider_folders):
    logger.warning("File %s is not executable, skipping", filename)
```

2023-11-18 01:59 UTC, alexandredosim commented
I accidentally closed the pull request by deleting the branch on my repository. Could anyone reopen it?

2023-12-02 22:35 UTC, kissiel commented
We really appreciate the contribution, but having spent quite some time to help this cause I decided there's no easy way to improve the current situation. 

The PR here improves the message by printing that the file that's being ignored is due to a fact that it's not executable, but that's only one of the reasons for the warnings. The real set of reasons is that the all of the classifiers failed to identify the file. The classifiers are defined [in the v1.py, starting here](https://github.com/canonical/checkbox/blob/main/checkbox-ng/plainbox/impl/secure/providers/v1.py#L442)

This means that adopting this patch would get us from a general warning message to a misleading one.

This is akin to running the GNU/Linux `file` utility. When it fails to detect what is the actual type of file being supplied, it just says "data". Doesn't state what classifiers it failed.

I'm afraid this may be a dead end for this development.

2023-12-02 22:35 UTC, closed without merging