Add testcase to check power-mode before and after suspend
canonical/checkbox pull request #824
Opened 2023-11-10 11:54 UTC by binli

## Description

With Platform Profile (low-power, balanced, performance) support being added to the kernel and GNOME we'd like this to be tested to confirm it is working during HW enablement/certification.
It is expected functionality on these platforms and we need to highlight any issues with it not working to the FW team so it can be fixed before preload signoff.

## Resolved issues

Original bug: https://bugs.launchpad.net/sutton/+bug/2036435

## Documentation
This testcase could help verify power mode can stay in the chosen setting after suspend.

## Tests

Outcome: job passed
==============[ Running job 6 / 7. Estimated time left: 0:00:02 ]===============
--------[ Dumps power_mode info to a file for comparison after suspend ]--------
ID: com.canonical.certification::suspend/power_mode_before_suspend
Category: com.canonical.plainbox::suspend
... 8< -------------------------------------------------------------------------
------------------------------------------------------------------------- >8 ---
Outcome: job passed
==============[ Running job 7 / 7. Estimated time left: 0:00:01 ]===============
----------------------[ suspend/power_mode_after_suspend ]----------------------
ID: com.canonical.certification::suspend/power_mode_after_suspend
Category: com.canonical.plainbox::suspend
... 8< -------------------------------------------------------------------------
------------------------------------------------------------------------- >8 ---
Outcome: job passed
Finalizing session that hasn't been submitted anywhere: checkbox-run-2023-11-10T11.52.36
==================================[ Results ]===================================
 ☑ : Create resource info for supported sleep states
 ☑ : Creates resource info for RTC
 ☑ : Automated test of suspend function
 ☑ : Collect information about kernel modules
 ☑ : Collect information about installed software packages
 ☑ : Dumps power_mode info to a file for comparison after suspend
 ☑ : suspend/power_mode_after_suspend

2024-01-10 01:42 UTC, pieqq requested changes
Sorry for the lack of feedback on this one...

I made a few comments and suggestions (you can accept them directly in GitHub and it will create a commit for you with the change).

The Python script will also require unit tests.

2024-01-12 14:14 UTC, kissiel commented
After talking with Binli we learned that he's busy ATM, so his PRs are on hold, and because they need work done on them I'm switching the state to "Draft"

2024-03-18 16:46 UTC, closed without merging

2024-03-26 07:05 UTC, binli commented on providers/base/units/suspend/suspend.pxu
> +
Thanks!

2024-04-03 16:10 UTC, binli commented on providers/resource/bin/power_mode_resource.py
> +def main():
Thank you. I've fixed it this issue.

2024-04-03 16:11 UTC, binli commented
I open another pull request, please help review it when you guys are free, https://github.com/canonical/checkbox/pull/1145 , thanks!