Fix gnome_randr_cycle not working under Wayland (LP:#2036172)(BugFix)
canonical/checkbox pull request #855
Opened 2023-11-30 13:52 UTC by hugh712

## Description

- Change the position of current_modes to earlier.
- Compare rate and existing_rate with float instead of string.

## Resolved issues
Currently runs 'gnome_randr_cycle.py' it will just directly finished without toggle any resolution, because some code glitch, after my change, it will work as expected. 

## Tests
I run code as below on my 22.04 laptop :
$ python3 /usr/lib/checkbox-provider-base/bin/gnome_randr_cycle.py --screenshot-dir=~/tmp
Set mode 1368x768@119.83 for output eDP-1
Set mode 1600x1200@89.91 for output eDP-1
Set mode 1920x1080@89.93 for output eDP-1
Set mode 1920x1200@120.00 for output eDP-1
Set mode 1920x1200@60.00 for output eDP-1

It will pick up a highest refresh rate in each resolution and find the top resolution per aspect, change resolution and get a screenshot, finally change back to original resolution, everything works as expected.

2023-12-05 05:53 UTC, hugh712 commented
@pieqq 

Would you please help to review my fix? thank you :)

2023-12-06 05:30 UTC, pieqq requested changes
@hugh712 thanks for this patch!

It seems your modifications are not passing the flake8 tests. From the tox run:

```
FAIL: test_flake8_/home/runner/work/checkbox/checkbox/providers/base/bin/gnome_randr_cycle.py (plainbox.provider_manager.Flake8Tests)
```

I added a few comments inline.

Also, did you check for regression? Have you tested your fix on X11? On 20.04?

2023-12-08 13:18 UTC, hugh712 commented
@pieqq 

Thanks for the review :)

For the question 
Also, did you check for regression? Have you tested your fix on X11? 
> As I know, this gnome_randr_cycle was designed for wayland, and xrandr_cycle.py for X11,
> So I am not sure to verify this gnome_randr_cycle under X11 is a valid test case?

2023-12-08 13:19 UTC, hugh712 commented on providers/base/bin/gnome_randr_cycle.py
> +            #ignore preferred for rate
done

2023-12-08 13:20 UTC, hugh712 commented on providers/base/bin/gnome_randr_cycle.py
> +            rate = rate.replace('+', '')
done

2023-12-12 06:47 UTC, pieqq commented
Thanks for the changes!

`gnome-randr` is compatible with both X11 and Wayland in theory, that's why I asked if you had done some regression testing, but after checking in our providers, we indeed only run this script when using Wayland, so no need to do this.

However, currently `gnome_randr_cycle.py` is not covered by any unit test. This is now a requirement for new PRs, as explained in the [Testing section of the Contributing Guide](https://github.com/canonical/checkbox/blob/main/CONTRIBUTING.md#testing).

Given that this script is a bit long and written in a very "imperative programming" style (I mean no functions, no classes, just running it line by line), it's gonna be difficult to test. I recommend you split the different parts into functions that should be easier to write unit tests for.

Reach out if you need help!

2024-01-10 01:52 UTC, pieqq commented
@hugh712 Hey! Did you have time to look into this to add some unit tests for your script? There are a few sections in the contrib guide that may help you:

- https://github.com/canonical/checkbox/blob/main/CONTRIBUTING.md#writing-and-running-unit-tests-for-providers
- https://github.com/canonical/checkbox/blob/main/CONTRIBUTING.md#coverage

2024-01-11 08:00 UTC, hugh712 commented
> @hugh712 Hey! Did you have time to look into this to add some unit tests for your script? There are a few sections in the contrib guide that may help you:
> 
> * https://github.com/canonical/checkbox/blob/main/CONTRIBUTING.md#writing-and-running-unit-tests-for-providers
> * https://github.com/canonical/checkbox/blob/main/CONTRIBUTING.md#coverage

@pieqq 

Hi Pierre,
This is still in my pocket, but unfortunately still can not find time to do that,
will let you know once I have progress, thank you :)

2024-01-12 14:19 UTC, kissiel commented
This PR awaits the author to have some time to work on it, and there's still some missing bits, so I'm switching the state to "Draft"

2024-10-11 09:23 UTC, Hook25 commented
Closing this as we completely changed how we set the resolution, fetch resolution but most importantly, it is basically inactive. Feel free to re-open it

2024-10-11 09:23 UTC, closed without merging