update the url to the stable PPA
canonical/checkbox pull request #860
Opened 2023-12-01 15:12 UTC by kissiel

## Description
A follow up to the PPA switch. This time for an lxd profile used by metabox.
## Tests

Tested by running metabox session.

2023-12-01 15:46 UTC, fernando79513 approved these changes
LGTM +1

2023-12-06 09:00 UTC, yphus requested changes
This PR is no longer valid. Changes introduced by https://github.com/canonical/checkbox/pull/866 make this patch obsolete.

2023-12-12 10:45 UTC, Hook25 approved these changes
This still has to change as the current value is not valid

2024-01-08 10:33 UTC, kissiel commented
This got ultimately fixed in https://github.com/canonical/checkbox/pull/859

2024-01-08 10:33 UTC, closed without merging