Restart agent properly in metabox (BugFix)
canonical/checkbox pull request #866
Opened 2023-12-04 12:45 UTC by kissiel

## Description

The previous "on-failure" meant that sending a signal to agent (for instance SIGKILL) would completely terminate the agent and make systemd not restart it.
This is very bad for emulating agent crashes. Thus I'm proposing here to `always` do it.

## Testing

Tested with MB runs using an agent-killing scenario.

2023-12-04 12:56 UTC, Hook25 approved these changes
+1, agree

EDIT: makes me wonder, should we also change the deb and snap? they have the same strategy

2023-12-04 14:20 UTC, Hook25 requested changes
If you want to change them all here, I'm fine with it but:
- change the title of the PR
- change also the deb service

2023-12-04 15:23 UTC, yphus requested changes
The service file provided by the checkbox-ng deb package also needs the same fix:
https://github.com/canonical/checkbox/blob/main/checkbox-ng/debian/checkbox-ng.service

2023-12-04 15:42 UTC, kissiel commented on checkbox-snap/series_classic16/snap/snapcraft.yaml
> +    restart-condition: always
Maybe let's do that even if only for consistency :)

2023-12-04 15:43 UTC, kissiel commented on metabox/metabox/lxd_profiles/checkbox.profile
This is explained in the PR description.

2023-12-04 15:48 UTC, kissiel commented
> The service file provided by the checkbox-ng deb package also needs the same fix: https://github.com/canonical/checkbox/blob/main/checkbox-ng/debian/checkbox-ng.service

Updated in a3c509e40ad54be855bb4bd591ce911b713c233e

2023-12-04 16:21 UTC, Hook25 approved these changes
+1, ty for updating them all!

2023-12-04 16:26 UTC, yphus approved these changes
LGTM

2023-12-05 10:38 UTC, Hook25 submitted a review, later dismissed
+1, ty

2023-12-05 13:05 UTC, yphus submitted a review, later dismissed
+1

2023-12-06 17:55 UTC, kissiel commented
I also removed the glxgears test that was silently failing before, but now it started failing properly and we really don't want to have it tested.

2023-12-06 17:55 UTC, Hook25 approved these changes
+1, ty

2023-12-07 09:04 UTC, merged