Change to new graphic test strategy - jobs and test plans (BugFix)
canonical/checkbox pull request #942
Opened 2024-01-17 01:05 UTC by hanhsuan

## Description
This is part of #586 that includes the changes of job and test plan only.

1. New jobs that uses prime_offload_tester.py to valid GPU rendering.
2. New test plans that conbimes integrated and discrete GPU into one.
3. Remove unnecessary jobs and test plans after switching to new graphic test strategy.

This PR depends on #586.
if #586 isn't merged yet, please don't merge this one.

## Resolved issues

## Documentation

## Tests

2024-01-24 05:40 UTC, pieqq approved these changes
Thanks for splitting up the work related to jobs and test plans, it males it easier to review!

I just made a few suggestions (you can accept them directly from within GitHub and it will create git commits automatically).

Otherwise, I think it's ready to land after #586 lands!

2024-01-24 05:40 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    Maunal-Test that glxgears works for {vendor} {product}
```suggestion
summary:
    Test that glxgears works for {vendor} {product} (manual)
description:
    Run glxgears while offloading rendering to the {vendor} {product} GPU
    and ask tester to validate the outcome.
```

2024-01-24 05:40 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    Auto-Test that glxgears works on fullscreen for {vendor} {product}
```suggestion
summary:
    Test that glxgears works in full screen mode for {vendor} {product} (automated)
description:
    Run glxgears in full screen mode while offloading rendering to the {vendor}
    {product} GPU and validate the outcome automatically.
```

2024-01-24 05:40 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    Maunal-Test that glxgears works on fullscreen for {vendor} {product}
```suggestion
summary:
    Test that glxgears works in full screen mode for {vendor} {product} (manual)
description:
    Run glxgears in full screen mode while offloading rendering to the {vendor}
    {product} GPU and as the tester to validate the outcome.
```

2024-01-24 05:40 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    1. Did the 3d animation appear?
```suggestion
    1. Did the 3D animation appear?
```

2024-01-24 05:48 UTC, hanhsuan commented
Thanks for your help !!!

2024-01-31 00:26 UTC, hanhsuan commented
@pieqq  After digging into [this issue](https://warthogs.atlassian.net/browse/OEMQA-3877?focusedCommentId=388179), I would like to change this PR to draft and make the jobs could match what gpu-manager do for Ubuntu.

2024-03-14 05:16 UTC, hanhsuan commented
We are going to separate the test cases of laptop and desktop and the reason is described  in #1027.

### submissions:
  - laptop:
    - [auto test](https://certification.canonical.com/hardware/202001-27667/submission/360073/)
    - [manual test](https://certification.canonical.com/hardware/202001-27667/submission/360075/)
  - desktop:
    - [auto test](https://certification.canonical.com/hardware/202401-33394/submission/360071/)
    - [manual test](https://certification.canonical.com/hardware/202401-33394/submission/360072/)

2024-03-19 00:39 UTC, hanhsuan commented
@pieqq  According to #1009, should I add template id and modify the test plan to use it?

2024-03-29 07:57 UTC, pieqq requested changes
My understanding is that you want to test things differently whether it's a laptop or a desktop.

However, for the laptop cases, you use

```
dmi.product in ['Notebook','Laptop','Portable','All In One','All-In-One','AIO','Convertible']
```

I think `'All In One','All-In-One','AIO'` belong to the desktop field. There are the kind of devices that embeds the motherboard into the screen, like an iMac for instance.

So I think you should review the requirements for the jobs you modified in this commit.

2024-03-29 07:57 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    dmi.product in ['Notebook','Laptop','Portable','All In One','All-In-One','AIO','Convertible']
```suggestion
    dmi.product in ['Notebook','Laptop','Portable','Convertible']
```

2024-03-29 07:57 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    dmi.product in ['Notebook','Laptop','Portable','All In One','All-In-One','AIO','Convertible']
```suggestion
    dmi.product in ['Notebook','Laptop','Portable','Convertible']
```

2024-03-29 07:57 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    dmi.product in ['Notebook','Laptop','Portable','All In One','All-In-One','AIO','Convertible']
```suggestion
    dmi.product in ['Notebook','Laptop','Portable','Convertible']
```

2024-03-29 07:57 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    dmi.product in ['Notebook','Laptop','Portable','All In One','All-In-One','AIO','Convertible']
```suggestion
    dmi.product in ['Notebook','Laptop','Portable','Convertible']
```

2024-03-29 07:57 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    dmi.product in ['Desktop','Low Profile Desktop','Tower','Mini Tower','Space-saving']
```suggestion
    dmi.product in ['Desktop','Low Profile Desktop','Tower','Mini Tower','Space-saving','All In One','All-In-One','AIO']
```

2024-03-29 07:57 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    dmi.product in ['Desktop','Low Profile Desktop','Tower','Mini Tower','Space-saving']
```suggestion
    dmi.product in ['Desktop','Low Profile Desktop','Tower','Mini Tower','Space-saving','All In One','All-In-One','AIO']
```

2024-03-29 08:42 UTC, hanhsuan commented
@pieqq  The reason to add AIO into prime offload test is that the behavior of graphic is the same with laptop. Some AIO will connect embedded monitor with iGPU and provide dGPU for performance mode. Therefore, we would like to cover this kind of condition.

2024-04-09 05:50 UTC, pieqq requested changes
Some rewording suggestions. Also, jobs with a `purpose` field don't need a `description` field, so I proposed changes to merge both with a simplified explanation.

2024-04-09 05:50 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
>       This test tests the basic 3D capabilities of your current video card
The `description` field is not required when there is a `purpose` field, so I suggest to merge both:

```suggestion
purpose:
     Tests the basic 3D capabilities of your current video card. This test covers all devices without an integrated display, such as desktops.
```

2024-04-09 05:50 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
>       This test tests the basic fullscreen 3D capabilities of your current video card
Same suggestion as above.

```suggestion
purpose:
     Tests the basic full screen 3D capabilities of your current video card. This test covers all devices without an integrated display, such as desktops.
```

2024-04-09 05:50 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    Test will cover all devices with integrated display, such as laptop and AIO.
```suggestion
    This test covers all devices with an integrated display, such as laptops and all-in-one (AIO) devices.
```

2024-04-09 05:50 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    Test will cover all devices with integrated display, such as laptop and AIO.
```suggestion
    This test covers all devices with an integrated display, such as laptops and all-in-one (AIO) devices.
```

2024-04-09 05:50 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    Test will cover all devices with integrated display, such as laptop and AIO.
```suggestion
    This test covers all devices with an integrated display, such as laptops and all-in-one (AIO) devices.
```

2024-04-09 05:50 UTC, pieqq commented on providers/base/units/graphics/jobs.pxu
> +    Test will cover all devices with integrated display, such as laptop and AIO.
```suggestion
    This test covers all devices with an integrated display, such as laptops and all-in-one (AIO) devices.
```

2024-04-10 08:59 UTC, pieqq approved these changes
+1

Thanks a lot for your determination!

2024-04-10 09:11 UTC, merged